config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :bookings
  resources :reports
  resources :contacts
  resources :rentals do
    resources :reviews
  end
  
  devise_for :users
  root 'rentals#index'

  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
    get '/users/password', to: 'devise/passwords#new'
  end
  
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :rental, dependent: :destroy
  belongs_to :user

  validates_presence_of :message
  
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @bookings = Booking.all
  end

  def show
  end

  def new
    @booking = current_user.bookings.build
  end

  def create
    @booking = current_user.bookings.build(booking_params)

    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: 'Booking successfully' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully cancelled' }
      format.json { head :no_content }
    end
  end

  private
    def set_booking
      @booking = Booking.find(params[:id])
    end

    def booking_params
      params.require(:booking).permit(:message, :status, :rental_id, :user_id)
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for(@booking) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :rental, label_method: :id, prompt: 'Select by House ID', label: false %>
    <%= f.input :message,input_html:{rows: 5}, label: false, placeholder: 'Message' %>
    
    <% if current_user && current_user.admin? %>
      <%= f.input :status, collection:['Approved', 'Rejected'], prompt: 'Take your action', label: false %>
    <% end %>
    <%= f.association :user, as: :hidden %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Submit", :class=>"btn btn-primary btn-md ml-0" %>
    <%= link_to "Back", bookings_path, :class=>"btn btn-dark btn-md"%>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<div class="container-fluid" style="margin-top: 15vh">
  <div class="row justify-content-center">
    <div class="col-sm-10 col-md-6 col-lg-6">
      <div class="card">
        <div class="card-body">
          <h4 class="card-text">Edit Booking</h4>
          <%= render 'form', booking: @booking %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<% if current_user && current_user.admin? %>
<div class="container-fluid" style="margin-top: 15vh">
  <div class="row justify-content-center">
    <div class="col-sm-12 col-lg-8 col-md-8">
      <div class="alert alert-success">
        Hi
        <strong>
          Owner
        </strong>
        !
        Currently You have
        <strong><%= @bookings.count %></strong>
        Booking Requests.
      </div>
    </div>
  </div>
</div>
<div class="container-fluid" style="margin-top: 5vh">
    <div class="row justify-content-center">
      <div class="col-sm-12 col-md-8 col-lg-8">
      <div class="table-responsive">
        <table class="table">
          <thead>
            <th>House ID</th>
            <th>Booking Date</th>
            <th>Client</th>
            <th>Booking Status</th>
            <th colspan="3">Actions</th>
          </thead>
          <tbody>
            <% @bookings.each do |booking| %>
              <tr>
                <td><%= link_to booking.rental.id, booking.rental %></td>
                <td><%= booking.created_at.strftime("%B, %d, %Y")%></td>
                <td><%= booking.user.email %></td>
                <td><%= booking.status %></td>
              
                <td><%= link_to 'Show', booking %></td>
                <td><%= link_to 'Cancel Booking', booking, method: :delete, data: { confirm: 'Are you sure to cancel the booking?' } %></td>
                <td><%= link_to 'Take Action', edit_booking_path(booking) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<% else %>
<div class="container-fluid" style="margin-top: 15vh">
  <div class="row justify-content-center">
    <div class="col-sm-12 col-lg-8 col-md-8">
      <div class="alert alert-success">
        Hi
        <strong>
          <%= current_user.email %>
        </strong>
        !
        Currently You have
        <strong><%= current_user.bookings.count %></strong>
        Booking.
      </div>
    </div>
  </div>
</div>

<% if !current_user.bookings.blank? %>
  <div class="container-fluid" style="margin-top: 5vh">
    <div class="row justify-content-center">
      <div class="col-sm-12 col-md-8 col-lg-8">
      <div class="table-responsive">
        <table class="table">
          <thead>
            <th>House ID</th>
            <th>Booking Date</th>
            <th>Booking Status</th>
            <th colspan="3">Actions</th>
          </thead>
          <tbody>
            <% current_user.bookings.each do |booking| %>
              <tr>
                <td><%= link_to booking.rental.id, booking.rental %></td>
                <td><%= booking.created_at.strftime("%B, %d, %Y")%></td>
                <td><%= booking.status %></td>
              
                <td><%= link_to 'Show', booking %></td>
                <td><%= link_to 'Cancel Booking', booking, method: :delete, data: { confirm: 'Are you sure to cancel the booking?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      </div>
      </div>
    </div>
  </div>
<% end %>

<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-sm-12 col-md-8 col-lg-8">
      <%= link_to 'New Booking', new_booking_path, :class=>"btn btn-success btn-md" %>
      <%= link_to "Back", root_path, :class=>"btn btn-dark btn-md"%>
    </div>
  </div>
</div>
<% end %>

app/views/bookings/new.html.erb
<div class="container-fluid" style="margin-top: 15vh">
  <div class="row justify-content-center">
    <div class="col-sm-10 col-md-6 col-lg-6">
      <div class="card">
        <div class="card-body">
          <h4 class="card-text">New Booking</h4>
          <%= render 'form', booking: @booking %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container-fluid" style="margin-top: 15vh">
  <div class="row justify-content-center">
    <div class="col-sm-12 col-md-8 col-lg-8">
      <div class="card">
        <div class="card-body">
            <div class="text-center"><%= image_tag(@booking.rental.image_url, :class=>"img-fluid", :size=>"280x360")%></div>
            <p class="mt-5">Booked House Number #<%= @booking.rental.id %></p>
            <p>Booked Date: <%= @booking.created_at.strftime("%B, %d, %Y")%></p>
            <p>Status: <%= @booking.status%></p>
            <hr>
            <p class="lead"><%= @booking.message %></p>
            <%= link_to "Back", bookings_path, :class=>"btn btn-primary btn-md ml-0"%>
            <% if current_user && current_user.admin? %>
              <%= link_to "Take Action", edit_booking_path, :class=>"btn btn-success btn-md"%>
            <% end %>
            <%= link_to "Cancel Booking", booking_path, method: :delete, data:{confirm: 'Are you sure?'}, :class=>"btn btn-danger btn-md"%>
        </div>
      </div>
    </div>
  </div>
</div>