config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :bookings
  resources :reports
  resources :contacts
  resources :rentals do
    resources :reviews
  end
  
  devise_for :users
  root 'rentals#index'

  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
    get '/users/password', to: 'devise/passwords#new'
  end
  
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :user
  has_many :reviews
  has_many :bookings

  validates_presence_of :location, :apartment_name, :block, :level, :house_number, :aircon, :room_number, :kitchen, :toilet, :balcony, :image_url, :washing_machine, :refrigerator, :oven, :electric_shower, :furniture_condition, :lift_facility, :payment, :available_seats

  def avg_score
    reviews.average(:score)
  end
  
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController

  load_and_authorize_resource
  before_action :set_rental, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @rentals = Rental.all.order('created_at DESC').where(["location like ?", "%#{params[:search]}%"]).paginate(page: params[:page], per_page: 8)
  end

  def show
    @review = Review.new
    @reviews = @rental.reviews.order('created_at DESC')
  end

  def new
    @rental = current_user.rentals.build
  end

  def edit
  end

  def create
    @rental = current_user.rentals.build(rental_params)

    respond_to do |format|
      if @rental.save
        format.html { redirect_to @rental, notice: 'Rental was successfully created.' }
        format.json { render :show, status: :created, location: @rental }
      else
        format.html { render :new }
        format.json { render json: @rental.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @rental.update(rental_params)
        format.html { redirect_to @rental, notice: 'Rental was successfully updated.' }
        format.json { render :show, status: :ok, location: @rental }
      else
        format.html { render :edit }
        format.json { render json: @rental.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @rental.destroy
    respond_to do |format|
      format.html { redirect_to rentals_url, notice: 'Rental was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_rental
      @rental = Rental.find(params[:id])
    end

    def rental_params
      params.require(:rental).permit(:location, :apartment_name, :block, :level, :house_number, :aircon, :room_number, :kitchen, :toilet, :balcony, :image_url, :washing_machine, :refrigerator, :oven, :electric_shower, :furniture_condition, :other_facilities, :lift_facility, :payment, :available_seats, :user_id)
    end
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/views/rentals/_form.html.erb
<%= simple_form_for(@rental) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-group row pt-4">
      <div class="col-sm-4">
        <%= f.input :location, label: 'LOCATION', collection: ['Taman Bahtera'], prompt:'Select Apartment Location' %>
      </div>
      <div class="col-sm-4">
        <%= f.input :apartment_name, label: 'NAME', placeholder: 'Enter Apartment Name' %>
      </div>
      <div class="col-sm-4">
        <%= f.input :block, label: 'BLOCK', collection: ['N/A',1,2,3,4,5,6,7,8,9,10], prompt:'Select Apartment Block' %>
      </div>
    </div>

    <div class="form-group row">
      <div class="col-sm-4">
        <%= f.input :level, label: 'LEVEL', collection: ['N/A','UG','G',1,2,3,4,5,6,7,8,9,10], prompt:'Select Apartment Level' %>
      </div>
      <div class="col-sm-4">
        <%= f.input :house_number, label: 'HOUSE NUMBER', placeholder: 'Enter House Number' %>
      </div>
      <div class="col-sm-4">
        <%= f.input :room_number, label: 'NUMBER OF ROOMS', collection: [1,2,3,4,5,6], prompt:'Select Number Of Total Rooms' %>
      </div>
    </div>

    <div class="form-group row">
      <div class="col-sm-4">
        <%= f.input :aircon, label: 'AIRCON', collection: ['Yes', 'No'], prompt:'Select Aircon Availability' %>
      </div>
      <div class="col-sm-4">
        <%= f.input :kitchen, label: 'KITCHEN', collection: ['Yes', 'No'], prompt:'Select Kitchen Availability' %>
      </div>
      <div class="col-sm-4">
        <%= f.input :toilet, label: 'NUMBER OF TOILETS', collection: [1,2,3,4], prompt:'Select Number Of Total Toilets' %>
      </div>
    </div>

    <div class="form-group row">
      <div class="col-sm-4">
        <%= f.input :balcony, label: 'BALCONY', collection: ['Yes', 'No'], prompt:'Select Balcony Availability' %>
      </div>
      <div class="col-sm-4">
        <%= f.input :washing_machine, label: 'WASHING MACHINE', collection: ['Yes', 'No'], prompt:'Select Washing M/C Availability' %>
      </div>
      <div class="col-sm-4">
        <%= f.input :refrigerator, label: 'REFRIGERATOR', collection: ['Yes', 'No'], prompt:'Select Refrigerator Availability' %>
      </div>
    </div>

    <div class="form-group row">
      <div class="col-sm-4">
        <%= f.input :oven, label: 'OVEN', collection: ['Yes', 'No'], prompt:'Select Oven Availability' %>
      </div>
      <div class="col-sm-4">
        <%= f.input :electric_shower, label: 'ELECTRIC SHOWER', collection: ['Yes', 'No'], prompt:'Select Electric Shower Availability' %>
      </div>
      <div class="col-sm-4">
        <%= f.input :furniture_condition, label: 'FURNITURE', collection: ['No', 'Yes, good condition', 'Yes, morderate good condition','Yes, not so good condition'], prompt:'Select Furniture Condition And Availability' %>
      </div>
    </div>

    <div class="form-group row">
      <div class="col-sm-4">
        <%= f.input :lift_facility, label: 'LIFT FACILITY', collection: ['Yes', 'No', 'Have, but in service'], prompt:'Select LIFT Availability' %>
      </div>

      <div class="col-sm-4">
        <%= f.input :image_url, label: 'Image URL', placeholder: 'Image URL' %>
      </div>

      <div class="col-sm-4">
        <%= f.input :available_seats, label: 'SEATS AVAILABLE FOR (n person)', collection:[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15], prompt: 'Select Seats(Vacancy) Available' %>
      </div>
    </div>

    <div class="form-group row">
      <div class="col-sm-12">
        <%= f.input :payment, label: 'COST / ADVANCE PAYMENT (MYR)',placeholder: 'Describe Cost / Advance Payment',input_html:{rows: 4} %>
      </div>
    </div>

    <div class="form-group row">
      
      <div class="col-sm-12">
        <%= f.input :other_facilities, label: 'OTHER FACILITIES (OPTIONAL)', placeholder: 'Other Facilities ... ',input_html:{rows: 6} %>
      </div>
    </div>

    <div class="form-inputs">
      <%= f.association :user, as: :hidden %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, "Submit",:class=>"btn btn-primary btn-sm ml-0" %>
      <%= link_to 'Back', rentals_path,:class=>"btn btn-secondary btn-sm" %>
    </div>
<% end %>

app/views/rentals/edit.html.erb
<% provide(:rentals_active, 'active') %>
<div class="container-fluid" style="margin-top: 12vh">
  <div class="row justify-content-center">
    <div class="col-sm-10">
      <div class="card" style="margin-bottom: 10px">
        <div class="card-body">
        <h3 class="text-center">EDIT THIS RENTAL INFORMATION</h3>
        <hr>
        <%= render 'form', rental: @rental %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rentals/index.html.erb
<div class="container-fluid">
  <div class="row justify-content-center" style="margin-top: 10vh">
    <div class="col-sm-12 d-flex">
    <div class="float-left">
    <% if current_user && current_user.admin? %>
      <%= link_to 'Add New', new_rental_path(@rental),:class=>"btn btn-secondary btn-sm" %>
    <% end %>
    </div>
      <div class="float-right" style="margin-top: -30px">
        <form class="form-inline md-form mb-2">
          <div class="form-group">
            <i class="fas fa-search ml-3" aria-hidden="true"></i>
          </div>
          <div class="form-group">
            <%= form_tag rentals_path, method: :get do %>
              <%= text_field_tag :search, params[:search], :class=>'form-control ml-3', placeholder:'Location' %>
            <% end %>
          </div>
        </form>
      </div>
    </div>
  </div>
  
  <div class="row justify-content-center">
    <% @rentals.each do |rental| %>
    <div class="col-sm-12 col-md-3 col-lg-3">
      <div class="card mb-2">
        <%= image_tag(rental.image_url, :class=>"card-img-top", :size=>"125x185")%>
        <div class="card-body">
          <h4 class="card-title mb-0">
            <i class="fas fa-map-marker-alt"></i> <%= rental.location %>
            | Block <%= rental.block %>
          </h4>
          <small class="text-muted">House ID: #<%= rental.id %></small>
          <p class="card-text"><i class="fas fa-clock mr-2"></i> Posted <%= time_ago_in_words(rental.created_at)%> ago
            <i class="fas fa-star ml-2"></i>
              <% if rental.avg_score %>
                <%= rental.avg_score %> / 5.0
              <% else %>
                0 / 5.0
              <% end %>
          </p>
          <p class="card-text text-justify"><%= truncate(rental.other_facilities, length: 100)%></p>
          <%= link_to "View", rental, :class=>"btn btn-primary btn-sm ml-0"%>
        </div>
      </div>
    </div>
    <% end %>
    
  </div>
</div>

<!-- Bootstrap4 Pagination + Will_Paginate + Bootstrap-will_paginate Gem -->
<nav aria-label="Page navigation example" style="margin-top: 10px">
  <ul class="pagination pg-blue justify-content-center">
            <%= will_paginate(@rentals,
            :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer,
            inner_window: 1,
            outer_window: 0,
            class: 'text-center') %>
  </ul>
</nav>
<!-- / Pagination -->

app/views/rentals/new.html.erb
<% provide(:rentals_active, 'active') %>
<div class="container-fluid" style="margin-top: 12vh">
  <div class="row justify-content-center">
    <div class="col-sm-10">
      <div class="card" style="margin-bottom: 10px">
        <div class="card-body">
        <h3 class="text-center">POST A NEW RENTAL</h3>
        <hr>
        <%= render 'form', rental: @rental %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rentals/show.html.erb
<% provide(:rentals_active, 'active') %>
<div class="container-fluid">
  <div class="row justify-content-center" style="margin-top: 10vh">
    <div class="col-sm-8 col-md-8 col-lg-8 mb-3">
      <div class="text-center"><%= image_tag(@rental.image_url, :size=>"512x740", :class=>"img-fluid mb-5")%></div>
      <div class="table-responsive">
        <table class="table">
          <tbody>
            <tr>
              <td>Location</td>
              <td><%= @rental.location%></td>
            </tr>
            <tr>
              <td>Apartment name</td>
              <td><%= @rental.apartment_name %></td>
            </tr>
            <tr>
              <td>Block</td>
              <td><%= @rental.block %></td>
            </tr>
            <tr>
              <td>Level</td>
              <td><%= @rental.level %></td>
            </tr>
            <tr>
              <td>House Number</td>
              <td><%= @rental.house_number %></td>
            </tr>
            <tr>
              <td>Aircon</td>
              <td><%= @rental.aircon %></td>
            </tr>
            <tr>
              <td>Numers Of Room(s)</td>
              <td><%= @rental.room_number %></td>
            </tr>
            <tr>
              <td>Kitchen(s)</td>
              <td><%= @rental.kitchen %></td>
            </tr>
            <tr>
              <td>Numers Of Toilet(s)</td>
              <td><%= @rental.toilet %></td>
            </tr>
            <tr>
              <td>Balocny</td>
              <td><%= @rental.balcony %></td>
            </tr>
            <tr>
              <td>Washing Machine</td>
              <td><%= @rental.washing_machine %></td>
            </tr>
            <tr>
              <td>Refrigerator</td>
              <td><%= @rental.refrigerator %></td>
            </tr>
            <tr>
              <td>Oven</td>
              <td><%= @rental.oven %></td>
            </tr>
            <tr>
              <td>Electric Shower</td>
              <td><%= @rental.electric_shower %></td>
            </tr>
            <tr>
              <td>Furniture</td>
              <td><%= @rental.furniture_condition %></td>
            </tr>
            <tr>
              <td>Lift Facility</td>
              <td><%= @rental.lift_facility %></td>
            </tr>
          </tbody>
        </table>
        <p class="lead text-justify"><%= @rental.other_facilities %></p>
        <%= link_to 'Back', rentals_path, :class=>"btn btn-sm btn-primary ml-0" %>

        <% if can? :update, @rental %>
          <%= link_to 'Edit', edit_rental_path(@rental),:class=>"btn btn-success btn-sm" %>
        <% end %>

        <% if can? :destroy, @rental %>
          <%= link_to 'Delete', rental_path,:class=>"btn btn-danger btn-sm", data: { toggle: 'modal',target:'#large-Modal' },:class=>"btn-sm btn btn-danger waves-effect" %>
        <% end %>
        
        <% if can? :create, @rental %>
          <%= link_to 'Add New', new_rental_path(@rental),:class=>"btn btn-secondary btn-sm" %>
        <% end %>

        <div class="modal fade" id="large-Modal" tabindex="-1" role="dialog">
              <div class="modal-dialog modal-lg" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h4 class="modal-title"><i class="fas fa-exclamation-triangle"></i> Account Deletion</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <h5>Are you sure to delete?</h5>
                   </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-sm btn-default waves-effect " data-dismiss="modal">Close</button>
                    <%= link_to "Delete This Post", rental_path, data: { toggle: 'modal',target:'#large-Modal' },method: :delete,:class=>"btn btn-sm btn-danger waves-effect waves-light" %>
                  </div>

                </div>
              </div>
            </div>
      </div>
    </div>
    
  </div>
</div>

<% if @rental.reviews.blank? %>
<hr>
<div class="container-fluid">
    <div class="row justify-content-center">
      <div class="col-sm-8 col-md-8 col-lg-8 mb-3">
        <p class="lead">No reviews to load!</p>
      </div>
    </div>
</div>
<% else %>
  <hr>
  <div class="container-fluid">
    <div class="row justify-content-center">
      <div class="col-sm-8 col-md-8 col-lg-8 mb-3">
        <div class="rental-reviews">
          <% @reviews.each do |review| %>
            <div id="review_pane">
              <%= render 'reviews/review', review: review %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
<% end %>

<% if current_user && current_user.admin? %>
<% else %>
<% if user_signed_in? %>
    <div class="row justify-content-center">
      <div class="col-sm-8 col-md-8 col-lg-8">
      <div class="card card-2" style="margin-bottom: 5px;padding-bottom: 0px">
          <div class="card-body">
          <%= form_with model: [@rental, @review], remote: true do |f| %>
            <%= f.select :score, [1,2,3,4,5], prompt:'Select Score'%>
            <br><br>
            <%= f.text_area :message,:class=>"form-control",placeholder:'Write your honest review',rows:5  %>
            <div class="pt-2">
              <%= f.submit "Post",:class=>"btn btn-sm btn-success ml-0", remote: true %>
            </div>
          <% end %>
          </div>
          </div>
      </div>
    </div>
<% else %>
    <div class="row justify-content-center">
      <div class="col-sm-8 col-md-8 col-lg-8">
        <p class="lead ml-0">Please
        <%= link_to "Sign in", new_user_session_path %>
        to post your review!</p>
      </div>
    </div>
<% end %>
<% end %>
  </div>