config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :bookings
  resources :reports
  resources :contacts
  resources :rentals do
    resources :reviews
  end
  
  devise_for :users
  root 'rentals#index'

  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
    get '/users/password', to: 'devise/passwords#new'
  end
  
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user

  validates_presence_of :title, :message
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  before_action :set_report, only: [:destroy]
  before_action :authenticate_user!

  def index
    @reports = Report.all
  end

  def new
    @report = current_user.reports.build
  end

  def create
    @report = current_user.reports.build(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to root_path, notice: 'Report was successfully posted.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Report was successfully removed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_report
      @report = Report.find(params[:id])
    end

    def report_params
      params.require(:report).permit(:title, :message, :user_id)
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<%= simple_form_for(@report) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title, label: false, placeholder:'Title' %>
    <%= f.input :message, label: false, placeholder:'Your message', input_html:{rows: 6} %>
    <%= f.association :user, as: :hidden %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Submit",:class=>"btn btn-sm btn-success" %>
    <%= link_to "Back", reports_path, :class=>"btn btn-sm btn-primary"%>
  </div>
<% end %>

app/views/reports/index.html.erb
<% provide(:reports_active, 'active') %>

<% if current_user && current_user.admin? %>
  <div class="container-fluid">
    <div class="row" style="margin-top: 10vh">
      <% @reports.each do |report| %>
        <div class="col-sm-12 col-md-6 col-lg-6">
          <div class="card">
            <div class="card-body">
              <div class="float-right">
                <%= link_to 'Delete', report, method: :delete, data: { confirm: 'Are you sure?' },:class=>"btn btn-sm btn-danger" %>
              </div>

              <h4 class="card-title"><%= report.title %></h4>
              <i class="far fa-clock"></i>
              <small class="text-muted"><%= time_ago_in_words(report.created_at) %>
              ago by
              <% if report.user.name? %>
                <%= report.user.name %>
              <% else %>
                <%= report.user.email %>
              <% end %>
              </small>
              <p class="card-text"><%= report.message %></p>
            </div>
          </div>
          <br>
        </div>
      <% end %>
    </div>
  </div>
<% else %>
<div class="container-fluid" style="margin-top: 20vh">
  <div class="row justify-content-center">
    <div class="col-sm-6 col-md-6 col-lg-6">
      <div class="text-center">
        <%= link_to '+ New Report', new_report_path,:class=>"btn btn-md btn-primary" %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/reports/new.html.erb
<div class="container" style="margin-top: 15vh">
  <div class="row justify-content-center">
    <div class="col-sm-12 col-md-8 col-lg-8">
      <div class="card">
        <div class="card-body">
          <h4 class="text-center mb-5">Submit A Report</h4>
          <%= render 'form', report: @report %>
        </div>
      </div>
    </div>
  </div>
</div>