config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :bookings
  resources :reports
  resources :contacts
  resources :rentals do
    resources :reviews
  end
  
  devise_for :users
  root 'rentals#index'

  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
    get '/users/password', to: 'devise/passwords#new'
  end
  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)  
    user ||= User.new
    if user.admin?
        #can :manage, :all
        can :create, Rental
        can :read, Rental
        can :update, Rental
        can :destroy, Rental

        can :read, Report
        can :destroy, Report

        can :read, Contact
        can :destroy, Contact

        can :read, Booking
        can :destroy, Booking
        can :update, Booking

    else
        can :create, Report
        
        can :read, Rental

        can :create, Booking
        can :read, Booking, user_id: user.id
        can :destroy, Booking, user_id: user.id

        can :create, Contact
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :rental, dependent: :destroy
  belongs_to :user

  validates_presence_of :message
  
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
  validates_presence_of :message
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :user
  has_many :reviews
  has_many :bookings

  validates_presence_of :location, :apartment_name, :block, :level, :house_number, :aircon, :room_number, :kitchen, :toilet, :balcony, :image_url, :washing_machine, :refrigerator, :oven, :electric_shower, :furniture_condition, :lift_facility, :payment, :available_seats

  def avg_score
    reviews.average(:score)
  end
  
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user

  validates_presence_of :title, :message
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :rental

  validates :user_id, :uniqueness => { :scope => :rental_id,
    :message => "Users may only write one review." }

  validates_presence_of :score, :message
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :rentals
  has_many :reviews
  has_many :contacts
  has_many :reports
  has_many :bookings

  def active_for_authentication?
    super && account_active?
  end

  def inactive_message
    account_active? ? super : :account_inactive
  end
  
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @bookings = Booking.all
  end

  def show
  end

  def new
    @booking = current_user.bookings.build
  end

  def create
    @booking = current_user.bookings.build(booking_params)

    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: 'Booking successfully' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully cancelled' }
      format.json { head :no_content }
    end
  end

  private
    def set_booking
      @booking = Booking.find(params[:id])
    end

    def booking_params
      params.require(:booking).permit(:message, :status, :rental_id, :user_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController

  load_and_authorize_resource
  before_action :set_rental, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @rentals = Rental.all.order('created_at DESC').where(["location like ?", "%#{params[:search]}%"]).paginate(page: params[:page], per_page: 8)
  end

  def show
    @review = Review.new
    @reviews = @rental.reviews.order('created_at DESC')
  end

  def new
    @rental = current_user.rentals.build
  end

  def edit
  end

  def create
    @rental = current_user.rentals.build(rental_params)

    respond_to do |format|
      if @rental.save
        format.html { redirect_to @rental, notice: 'Rental was successfully created.' }
        format.json { render :show, status: :created, location: @rental }
      else
        format.html { render :new }
        format.json { render json: @rental.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @rental.update(rental_params)
        format.html { redirect_to @rental, notice: 'Rental was successfully updated.' }
        format.json { render :show, status: :ok, location: @rental }
      else
        format.html { render :edit }
        format.json { render json: @rental.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @rental.destroy
    respond_to do |format|
      format.html { redirect_to rentals_url, notice: 'Rental was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_rental
      @rental = Rental.find(params[:id])
    end

    def rental_params
      params.require(:rental).permit(:location, :apartment_name, :block, :level, :house_number, :aircon, :room_number, :kitchen, :toilet, :balcony, :image_url, :washing_machine, :refrigerator, :oven, :electric_shower, :furniture_condition, :other_facilities, :lift_facility, :payment, :available_seats, :user_id)
    end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  before_action :set_report, only: [:destroy]
  before_action :authenticate_user!

  def index
    @reports = Report.all
  end

  def new
    @report = current_user.reports.build
  end

  def create
    @report = current_user.reports.build(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to root_path, notice: 'Report was successfully posted.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Report was successfully removed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_report
      @report = Report.find(params[:id])
    end

    def report_params
      params.require(:report).permit(:title, :message, :user_id)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :set_rental
	before_action :authenticate_user!, only:[:create, :destroy]
	
	def create
		@review = @rental.reviews.new(review_params)
		@review.user = current_user
		@review.save
		redirect_back(fallback_location: root_path)
	end

	def destroy
		@review = @rental.reviews.find(params[:id])
		@review_id = @review.id
		@review.destroy
	end

	private
	def review_params
		params.require(:review).permit(:message, :score, :rental_id)
	end
	def set_rental
		@rental = Rental.find(params[:rental_id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_navbar_admin.html.erb
<header>
  <nav class="navbar fixed-top navbar-expand-lg navbar-light #fafafa grey lighten-5 scrolling-navbar">
    <div class="container-fluid">
      <strong>
        <%= link_to "UKLK RENTAL SYSTEM", root_path, :class=>"navbar-brand" %>
      </strong>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <%= link_to "Find House", root_path, :class=>"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Booking Requests", bookings_path, :class=>"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Reports", reports_path, :class=>"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Contacts", contacts_path, :class=>"nav-link"%>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
              <% if current_user.name? %>
                <%= current_user.name %>
              <% else %>
                <%= current_user.email %>
              <% end %>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
              <%= link_to edit_user_registration_path, :class=>"dropdown-item" do %>
                <i class="fas fa-cog mr-2"></i> Account Setup
              <% end %>
              <%= link_to rails_admin_path, :class=>"dropdown-item" do %>
                <i class="fas fa-chart-line mr-2"></i> Dashboard
              <% end %>

              <%= link_to destroy_user_session_path, method: :delete, :class=>"dropdown-item" do %>
                <i class="fas fa-sign-out-alt mr-2"></i> Log-Out
              <% end %>

            </div>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_navbar_default.html.erb
<header>
  <nav class="navbar fixed-top navbar-expand-lg navbar-light #fafafa grey lighten-5 scrolling-navbar">
    <div class="container-fluid">
      <strong>
        <%= link_to "UKLK RENTAL SYSTEM", root_path, :class=>"navbar-brand" %>
      </strong>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item <%= yield(:home_active) %>">
            <%= link_to "Find House", root_path, :class=>"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Booking", bookings_path, :class=>"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Report", reports_path, :class=>"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Contact", contacts_path, :class=>"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, :class=>"btn btn-sm btn-secondary" %>
          </li>
          <li class="nav-item">
            <%= link_to "Join", new_user_registration_path, :class=>"btn btn-sm btn-info" %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_navbar_student.html.erb
<header>
  <nav class="navbar fixed-top navbar-expand-lg navbar-light #fafafa grey lighten-5 scrolling-navbar">
    <div class="container-fluid">
      <strong>
        <%= link_to "UKLK RENTAL SYSTEM", root_path, :class=>"navbar-brand" %>
      </strong>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <%= link_to "Find House", root_path, :class=>"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Booking", bookings_path, :class=>"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Report", reports_path, :class=>"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Contact", contacts_path, :class=>"nav-link"%>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
              <% if current_user.name? %>
                <%= current_user.name %>
              <% else %>
                <%= current_user.email %>
              <% end %>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
              <%= link_to edit_user_registration_path, :class=>"dropdown-item" do %>
                <i class="fas fa-cog mr-2"></i> Account Setup
              <% end %>

              <%= link_to destroy_user_session_path, method: :delete, :class=>"dropdown-item" do %>
                <i class="fas fa-sign-out-alt mr-2"></i> Log-Out
              <% end %>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UKLK Rental System</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag('home.png') %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/css/mdb.min.css" rel="stylesheet">
  </head>
  <body>
    <% if user_signed_in? %>
      <% if current_user && current_user.admin? %>
        <%= render 'layouts/navbar_admin' %>
      <% else %>
        <%= render 'layouts/navbar_student' %>
      <% end %>
    <% else %>
      <%= render 'layouts/navbar_default' %>
    <% end %>
    <%= yield %>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/js/mdb.min.js"></script>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>